- id: 10
  pose:
    pose:
      position:
        x: 0.0
        y: 0.3
        z: 0.0
      orientation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
    covariance: [50,0,0,0,0,0, 0,50,0,0,0,0, 0,0,0,0,0,0, 0,0,0,0,0,0, 0,0,0,0,0,0, 0,0,0,0,0,0]
